
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Oct 15 2024 00:30:03 UTC (Oct 15 2024 00:30:03 UTC)

// Verification Directory fv/lods_sw_12 

module lods_sw_12(a, c, v);
  input [11:0] a;
  output [3:0] c;
  output v;
  wire [11:0] a;
  wire [3:0] c;
  wire v;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_12, n_15, n_16, n_17;
  sky130_fd_sc_hd__a221o_1 g424__2398(.A1 (n_16), .A2 (n_17), .B1
       (n_17), .B2 (a[9]), .C1 (a[11]), .X (c[0]));
  sky130_fd_sc_hd__nor2_1 g425__5107(.A (a[8]), .B (n_15), .Y (n_16));
  sky130_fd_sc_hd__nor2_1 g428__6260(.A (a[7]), .B (n_12), .Y (n_15));
  sky130_fd_sc_hd__or3_1 g426__4319(.A (a[1]), .B (c[3]), .C (n_9), .X
       (v));
  sky130_fd_sc_hd__nor2_1 g429__8428(.A (a[6]), .B (n_10), .Y (n_12));
  sky130_fd_sc_hd__a211o_1 g427__5526(.A1 (n_6), .A2 (n_3), .B1
       (a[11]), .C1 (a[10]), .X (c[1]));
  sky130_fd_sc_hd__nor2_1 g432__6783(.A (a[5]), .B (n_4), .Y (n_10));
  sky130_fd_sc_hd__nand3b_1 g430__3680(.A_N (a[0]), .B (n_7), .C (n_5),
       .Y (n_9));
  sky130_fd_sc_hd__nor2_1 g431__1617(.A (n_7), .B (c[3]), .Y (c[2]));
  sky130_fd_sc_hd__o31ai_1 g433__2802(.A1 (a[4]), .A2 (a[5]), .A3
       (n_5), .B1 (n_2), .Y (n_6));
  sky130_fd_sc_hd__nor2_1 g434__1705(.A (a[4]), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__nand3b_1 g436__5122(.A_N (a[11]), .B (n_3), .C
       (n_17), .Y (c[3]));
  sky130_fd_sc_hd__nor3b_1 g435__8246(.A (a[4]), .B (a[5]), .C_N (n_2),
       .Y (n_7));
  sky130_fd_sc_hd__a21oi_1 g437__7098(.A1 (n_0), .A2 (a[1]), .B1
       (a[3]), .Y (n_1));
  sky130_fd_sc_hd__nor2_1 g440__6131(.A (a[8]), .B (a[9]), .Y (n_3));
  sky130_fd_sc_hd__nor2_1 g438__1881(.A (a[2]), .B (a[3]), .Y (n_5));
  sky130_fd_sc_hd__nor2_1 g439__5115(.A (a[6]), .B (a[7]), .Y (n_2));
  sky130_fd_sc_hd__inv_1 g442(.A (a[10]), .Y (n_17));
  sky130_fd_sc_hd__inv_1 g441(.A (a[2]), .Y (n_0));
endmodule

